### PR TITLE
Phiz adaptor

### PR DESCRIPTION
**Pull request by grillo-delmal**
Yesterday searching for things about mocap I found this project https://www.phizmocap.dev/. Since it implements exporting tracking values and blendshapes through OSC, I implemented it in facetrack-d and session for testing purposes.

My first impression is that it's easier to use than OSF, but I still have my concerns considering that it runs on a webpage on the browser (and I still haven't had the chance to study that part).

To test this, you also need the PR branch from facetrack-d

Resubmitted since https://github.com/Inochi2D/facetrack-d/pull/16 was merged

### CODE REVIEW

**Comment by grillo-delmal** [comment]
Forgot that session still depends on the sable version of facetrack-d xD

**Comment by LunaTheFoxgirl** [comment]
Since the PhizAdaptor is hidden behind a version tag, session should test for said version tag too, to prevent invalid compilation when Phiz is not enabled.

**Comment by grillo-delmal** [comment]
makes sense, I'll look into it

**Comment by grillo-delmal** [comment]
Ok, looked into it, and everything is working as expected in this commit, but it seems I need to clarify some things (I wrote this half a year ago, so I didn't remember how it was implemented :sweat_smile: )

Regarding the included version tag, I forgot to mention that https://www.phizmocap.dev/ provides multiple protocol implementations, between them, the OSC one that I mentioned in the PR and a websocket based one. 

I implemented the OSC one as PhizOSCAdaptor in facetrack-d, that one is not behind a version tag since it doesn't require any extra dependencies to work. I also implemented the websocket protocol from that page as the PhizAdaptor, but that one requires vibe-d to run, so I hid it behind a version tag (the same way the JML and the websocket adaptor are implemented). 

The version flag is activated if you compile the facetrack-d library with the web-adaptors config. You can trigger this through the session build process compiling it with the ` --override-config=facetrack-d/web-adaptors` flag.

I ended up implementing both of them because the websocket one is a bit more convenient to use. This is because the OSC one requires an external app that you need to run in your PC for it to work.

Regarding my research about it, I used the webapp for around a couple of month and works fine for tracking, but I stopped using it since Puppetstring has become a way better alternative.

If you want to test if the web-adaptors for new PRs, you can apply the folowing patch to the github workflow file
```diff
diff --git a/.github/workflows/pr-test.yml b/.github/workflows/pr-test.yml
index 04b80f1..89822e6 100644
--- a/.github/workflows/pr-test.yml
+++ b/.github/workflows/pr-test.yml
@@ -38,6 +38,10 @@ jobs:
         # Build metadata (like version information and icons)
         dub build --config=meta
 
+        # Build the project with facetrack-d/web-adaptors enabled, with its main file included, without unittests
+        dub build --compiler=ldc2 --build=release --config=linux-full --override-config=facetrack-d/web-adaptors
+        mv out out-web-adaptors
+
         # Build the project, with its main file included, without unittests
         dub build --compiler=ldc2 --build=release --config=linux-full
 
@@ -46,4 +50,11 @@ jobs:
       uses: actions/upload-artifact@v3
       with:
         name: inochi-session
-        path: out/
\ No newline at end of file
+        path: out/
+
+    - name: "Upload Web Adaptors Artifacts"  
+      if: success()
+      uses: actions/upload-artifact@v3
+      with:
+        name: inochi-session-web-adaptors
+        path: out-web-adaptors/
```

**Pull request merged**
